prometheus:
  prometheusSpec:
    disableCompaction: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    thanos:
      image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-config
          key: thanos-storage-config.yaml

  thanosService:
    enabled: true
    annotations: {}
    labels: {}
    externalTrafficPolicy: Cluster
    type: ClusterIP
    portName: grpc
    port: 10901
    targetPort: "grpc"
    httpPortName: http
    httpPort: 10902
    targetHttpPort: "http"
    clusterIP: ""
    nodePort: 30901
    httpNodePort: 30902